# SwiftLint Configuration for CoverCraft
# Strict linting rules for high code quality

# Include/exclude paths
included:
  - CoverCraftPackage/Sources
  - CoverCraft
excluded:
  - CoverCraftPackage/.build
  - CoverCraftPackage/Tests  # Tests can be more lenient
  - .build
  - DerivedData
  - docs

# Analyzer rules (require building)
analyzer_rules:
  - unused_import
  - unused_declaration

# Rule configuration
line_length: 120
file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 75

type_body_length:
  warning: 200
  error: 300

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3

# Enabled rules (strict set)
opt_in_rules:
  # Performance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - sorted_first_last
  
  # Correctness
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - legacy_random
  - strong_iboutlet
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - yoda_condition
  
  # Style
  - attributes_order
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
  - function_default_parameter_at_end
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_imports
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unneeded_break_in_switch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  
  # Documentation
  - missing_docs

# Disabled rules
disabled_rules:
  - todo  # Allow TODO comments during development
  - multiple_closures_with_trailing_closure  # SwiftUI uses this pattern

# Custom rule configuration
attributes_order:
  order:
    - "@IBAction"
    - "@IBOutlet"
    - "@IBInspectable"
    - "@GKInspectable"
    - "@NSManaged"
    - "@objc"
    - "@nonobjc"
    - "@discardableResult"
    - "@MainActor"
    - "@Observable"
    - "@Sendable"
    - "public"
    - "internal"
    - "fileprivate"
    - "private"
    - "static"
    - "class"
    - "final"
    - "required"
    - "convenience"
    - "override"

file_header:
  required_pattern: |
                    \/\/ Version: \d+\.\d+\.\d+
                    \/\/ .*

file_types_order:
  order:
    - main_type
    - extension
    - preview_provider

missing_docs:
  excludes_extensions: false
  excludes_inherited_types: false

modifier_order:
  preferred_order:
    - "override"
    - "public"
    - "internal"
    - "fileprivate"
    - "private"
    - "@MainActor"
    - "@objc"
    - "static"
    - "final"
    - "required"
    - "convenience"

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  allows_single_line: false

number_separator:
  minimum_length: 5
  minimum_fraction_length: 5

sorted_imports:
  grouped_imports: true

type_contents_order:
  order:
    - associated_type
    - type_alias
    - case
    - static_property
    - instance_property
    - ib_outlet
    - initializer
    - type_method
    - instance_method
    - subscript
    - subtype

vertical_whitespace:
  max_empty_lines: 2

# Custom rules
custom_rules:
  # Enforce actor isolation annotations
  actor_isolation:
    name: "Actor Isolation"
    regex: "(?<!@MainActor\\s)(?<!@GlobalActor\\s)(?<!actor\\s)class\\s+\\w+.*:\\s*.*ObservableObject"
    message: "Classes conforming to ObservableObject should use @MainActor or be actors"
    severity: warning

  # Enforce @Observable usage over ObservableObject
  observable_over_observable_object:
    name: "Prefer @Observable"
    regex: "ObservableObject"
    message: "Use @Observable macro instead of ObservableObject protocol"
    severity: warning

  # Ensure proper error handling
  force_try_warning:
    name: "Force Try"
    regex: "try!"
    message: "Avoid force try - use proper error handling"
    severity: warning

  # Encourage structured concurrency
  dispatch_queue_usage:
    name: "DispatchQueue Usage"
    regex: "DispatchQueue\\."
    message: "Consider using Swift Concurrency (async/await) instead of DispatchQueue"
    severity: warning

  # Enforce logging standards
  print_statement:
    name: "Print Statement"
    regex: "\\bprint\\("
    message: "Use os.Logger instead of print statements"
    severity: warning

# Reporter configuration
reporter: "github-actions-logging"